extends: airbnb-base

env:
  browser: true
  es6: true

rules:
  global-require:
    - 0
  arrow-parens:
    - 2
    - always
  newline-after-var:
    - 2
    - always
  newline-before-return:
    - 2
  newline-per-chained-call:
    - 2
    -
      ignoreChainWithDepth: 2
  no-multiple-empty-lines:
    - 2
    - max: 1
      maxEOF: 0
  no-param-reassign:
    - 0
  comma-dangle:
    - error
    - never
  quote-props:
    - error
    - consistent-as-needed
  max-len:
    - 2
    - code: 150
  no-use-before-define: off
  eol-last: error
